/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevRouteImport } from './routes/dev'
import { Route as FoundationRouteImport } from './routes/foundation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as CoursesCourseIdMaterialsFilenameRouteImport } from './routes/courses.$courseId_.materials.$filename'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationRoute = FoundationRouteImport.update({
  id: '/foundation',
  path: '/foundation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdMaterialsFilenameRoute =
  CoursesCourseIdMaterialsFilenameRouteImport.update({
    id: '/courses/$courseId_/materials/$filename',
    path: '/courses/$courseId/materials/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev': typeof DevRoute
  '/foundation': typeof FoundationRoute
  '/login': typeof LoginRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses/$courseId/materials/$filename': typeof CoursesCourseIdMaterialsFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev': typeof DevRoute
  '/foundation': typeof FoundationRoute
  '/login': typeof LoginRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses/$courseId/materials/$filename': typeof CoursesCourseIdMaterialsFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev': typeof DevRoute
  '/foundation': typeof FoundationRoute
  '/login': typeof LoginRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses/$courseId_/materials/$filename': typeof CoursesCourseIdMaterialsFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev'
    | '/foundation'
    | '/login'
    | '/courses/$courseId'
    | '/courses/$courseId/materials/$filename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev'
    | '/foundation'
    | '/login'
    | '/courses/$courseId'
    | '/courses/$courseId/materials/$filename'
  id:
    | '__root__'
    | '/'
    | '/dev'
    | '/foundation'
    | '/login'
    | '/courses/$courseId'
    | '/courses/$courseId_/materials/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevRoute: typeof DevRoute
  FoundationRoute: typeof FoundationRoute
  LoginRoute: typeof LoginRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesCourseIdMaterialsFilenameRoute: typeof CoursesCourseIdMaterialsFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundation': {
      id: '/foundation'
      path: '/foundation'
      fullPath: '/foundation'
      preLoaderRoute: typeof FoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId_/materials/$filename': {
      id: '/courses/$courseId_/materials/$filename'
      path: '/courses/$courseId/materials/$filename'
      fullPath: '/courses/$courseId/materials/$filename'
      preLoaderRoute: typeof CoursesCourseIdMaterialsFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevRoute: DevRoute,
  FoundationRoute: FoundationRoute,
  LoginRoute: LoginRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesCourseIdMaterialsFilenameRoute: CoursesCourseIdMaterialsFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
