#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVER="$ROOT/server"
APP="$ROOT/app"

# port_busy PORT: success if something already listens on 127.0.0.1:PORT.
port_busy() {
  (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null
}

# drop_env KEY removes KEY from ENV_FILE (used to clear a placeholder before asking).
drop_env() {
  [[ -f "$ENV_FILE" ]] || return 0
  local tmp; tmp=$(mktemp)
  grep -vE "^${1}=" "$ENV_FILE" > "$tmp" || true
  mv "$tmp" "$ENV_FILE"
}

banner "Course knowledge store: local development"

# ── 1. Tooling ────────────────────────────────────────────────────────────
stage "Tooling: uv, Node 26+, npm"
say "The backend is Python 3.14 managed by uv; the web app is Node 26+."

# Windows only. Cognee's embedded stores nest about 185 characters below COGNEE_ROOT
# (system/databases/<uuid>/<uuid>.lance.db/<Table>.lance/_transactions/<uuid>.txn, whose
# longest table is EdgeType_relationship_name). Past MAX_PATH the cognify dies inside
# LanceDB with "failed to persist temp file", which names nothing about path length and
# costs an afternoon to work out. LongPathsEnabled is per-machine and does not travel with
# a clone, so every Windows teammate meets this separately: hence the check here.
case "$(uname -s)" in
  MINGW* | MSYS* | CYGWIN*)
    _cognee_suffix="/.cognee/system"
    _cognee_used=$(( ${#SERVER} + ${#_cognee_suffix} ))
    _cognee_budget=75
    # Empty when the value is absent, which means the same as 0 here.
    _longpaths=$(reg query 'HKLM\SYSTEM\CurrentControlSet\Control\FileSystem' //v LongPathsEnabled 2>/dev/null \
      | sed -n 's/.*REG_DWORD *0x\([0-9a-fA-F]*\).*/\1/p' | tail -n1)
    if [[ -n "$_longpaths" ]] && (( 16#$_longpaths != 0 )); then
      say "Windows long paths are enabled; Cognee's deep store paths are fine."
    elif (( _cognee_used <= _cognee_budget )); then
      note "Long paths are off, but server/.cognee/system is $_cognee_used characters, inside the ~$_cognee_budget Cognee leaves. Fine."
    else
      warn "Windows long paths are off and this checkout is too deep for Cognee."
      say "server/.cognee/system is $_cognee_used characters; Cognee needs about $_cognee_budget or fewer."
      say "Cognify will fail with a LanceDB 'failed to persist temp file' error."
      step "Either enable long paths in an admin PowerShell, then reboot:"
      note '    New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" \'
      note '      -Name LongPathsEnabled -Value 1 -PropertyType DWORD -Force'
      step 'or move this checkout somewhere shorter, such as C:\dev\Lattice.'
      pause "Press Enter when one of those is done, or to continue and hit this later."
    fi
    ;;
esac
missing=0
if command -v uv >/dev/null 2>&1; then
  say "uv $(uv --version | cut -d' ' -f2) found."
else
  missing=1
  warn "uv is not installed."
  open_url "https://docs.astral.sh/uv/getting-started/installation/"
  step "Install uv (macOS/Linux: curl -LsSf https://astral.sh/uv/install.sh | sh), then open a new shell."
fi
if command -v node >/dev/null 2>&1; then
  node_major=$(node -v | sed 's/^v//' | cut -d. -f1)
  if (( node_major >= 26 )); then
    say "node $(node -v) found."
  else
    missing=1
    warn "node $(node -v) is too old; app/package.json requires >=26."
    open_url "https://nodejs.org/en/download"
    step "Install Node 26 or newer (nvm: nvm install 26 && nvm use 26)."
  fi
else
  missing=1
  warn "node is not installed."
  open_url "https://nodejs.org/en/download"
  step "Install Node 26 or newer, then open a new shell."
fi
if (( missing )); then
  pause "Re-run this wizard once the tools above are installed. Press Enter to exit."
  exit 1
fi
note "Python 3.14 itself is installed by uv in the next stage; nothing to do for it."
pause

# ── 2. Backend dependencies ───────────────────────────────────────────────
stage "Backend: install Python and dependencies"
say "Runs 'uv sync' in server/: fetches Python 3.14, Cognee 1.5.4, fastembed and friends."
note "First run downloads a few hundred MB."
( cd "$SERVER" && uv sync )
say "server/.venv is ready."
pause

# ── 3. DeepSeek key ───────────────────────────────────────────────────────
stage "DeepSeek: LLM API key"
ENV_FILE="$SERVER/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  cp "$SERVER/.env.example" "$ENV_FILE"
  drop_env LLM_API_KEY   # remove the sk-... placeholder so it is not offered as a default
  say "Created server/.env from .env.example (DeepSeek V4 Flash, local fastembed embeddings)."
else
  say "server/.env exists; only the key is asked for. Other values are kept."
fi
say "Cognify (entity extraction) and answers run on DeepSeek V4 Flash. Embeddings are local; no second key."
open_url "https://platform.deepseek.com/api_keys"
step "Sign in, click 'Create new API key', name it (e.g. lattice-dev), copy the key (starts sk-)."
step "Top-up is required before the key works; a few dollars covers weeks of development."
ask_secret LLM_API_KEY "Paste the DeepSeek API key:"
while [[ -z "$LLM_API_KEY" || "$LLM_API_KEY" == "sk-..." ]]; do
  warn "A key is required; cognify cannot run without it."
  ask_secret LLM_API_KEY "Paste the DeepSeek API key:"
done
write_env LLM_API_KEY "$LLM_API_KEY"
say "Checking the key against DeepSeek with a tiny completion..."
if ( cd "$SERVER" && uv run --no-sync python - <<'PY'
import os
from dotenv import load_dotenv
load_dotenv(".env")
import litellm
r = litellm.completion(
    model=os.environ["LLM_MODEL"], api_key=os.environ["LLM_API_KEY"],
    api_base=os.environ["LLM_ENDPOINT"],
    messages=[{"role": "user", "content": "Reply with the single word OK."}], max_tokens=20,
)
print("  DeepSeek replied:", r.choices[0].message.content.strip())
PY
); then
  say "Key works."
else
  warn "DeepSeek rejected the key (or the account has no balance). Fix it, then re-run this wizard."
  exit 1
fi
pause

# ── 4. Ports ──────────────────────────────────────────────────────────────
stage "Ports: API and web app"
say "The API defaults to :8000 and the web app to :3000. The web app is told where the API is via app/.env."
API_PORT=8000
if port_busy "$API_PORT"; then
  warn "Something already listens on :8000."
  ask API_PORT_INPUT "API port to use instead [8010]:"
  API_PORT="${API_PORT_INPUT:-8010}"
fi
if port_busy 3000; then
  warn "Something already listens on :3000. Stop it, or run the web app with 'npm run dev -- --port <n>' and add that origin to CORS_ORIGINS in server/.env."
fi
ENV_FILE="$APP/.env"
write_env VITE_API_URL "http://localhost:${API_PORT}"
ENV_FILE="$SERVER/.env"
note "server/.env keeps CORS_ORIGINS=[\"http://localhost:3000\"] and DEV_HEADER_AUTH=true (the X-User header is the login)."
pause

# ── 5. Web app dependencies ───────────────────────────────────────────────
stage "Web app: install dependencies"
say "Runs 'npm install' in app/."
( cd "$APP" && npm install )
say "app/node_modules is ready."
pause

# ── 6. Embedding model ────────────────────────────────────────────────────
stage "Embeddings: download the local model"
say "Cognee embeds with fastembed on the CPU. The model (~130 MB) is fetched on first cognify;"
say "fetching it now keeps the first upload from looking stuck."
if confirm "Download BAAI/bge-small-en-v1.5 now?"; then
  ( cd "$SERVER" && uv run --no-sync python - <<'PY'
import os
from dotenv import load_dotenv
load_dotenv(".env")
from fastembed import TextEmbedding
TextEmbedding(os.environ.get("EMBEDDING_MODEL", "BAAI/bge-small-en-v1.5"))
print("  model cached")
PY
  )
else
  note "Skipped; the first material upload will download it."
fi
pause

# ── 7. Run it ─────────────────────────────────────────────────────────────
stage "Run: two terminals"
say "Everything is configured. Start the two processes:"
printf '\n'
say "  cd server && uv run uvicorn lattice.main:app --reload --port ${API_PORT}"
say "  cd app && npm run dev"
printf '\n'
say "Then open http://localhost:3000, keep course 'cs101' and user 'alice@example.com',"
say "upload a .pdf/.pptx/.md, save a note, and ask. Change the user to see the private tier isolate."
note "API docs: http://localhost:${API_PORT}/docs. Cognee state lives in server/.cognee/ (ignored)."
note "The materials/notes list is in memory: an API restart empties it while the knowledge stays."
pause "Press Enter to finish."

finish
