#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────
# STAGES: seed a course's Materials into a local API, end to end.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

SERVER_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
ENV_FILE="${ENV_FILE:-$SERVER_DIR/.env}"
API="${API:-http://localhost:8000}"
cd "$SERVER_DIR"

banner "Seed a course"

stage "The course"
say "The course the Materials belong to. An existing code is reused, not duplicated."
ask COURSE_CODE "Course code, lowercase letters and digits (e.g. cs4223):"
COURSE_CODE=${COURSE_CODE:-cs4223}
ask COURSE_NAME "Course name (e.g. Multi-core Architectures):"
COURSE_NAME=${COURSE_NAME:-$COURSE_CODE}
SEED_DIR="$SERVER_DIR/data/seed/${COURSE_CODE^^}"
note "slides will be read from $SEED_DIR"
pause

stage "The slides"
say "Lecture files (.pdf, .pptx, .md, .txt), named like 'L02a - Cache Basics.pdf' so the"
say "wizard can fill in each Material's title and lecture number."
if compgen -G "$SEED_DIR/*" >/dev/null; then
  note "$SEED_DIR already holds $(find "$SEED_DIR" -maxdepth 1 -type f | wc -l | tr -d ' ') file(s)."
  confirm "Add more files from a zip or another directory?" || SKIP_IMPORT=1
fi
if [[ -z "${SKIP_IMPORT:-}" ]]; then
  step "Have the zip or folder of lecture files ready on this machine."
  ask SEED_SOURCE "Path to the zip or directory:"
  SEED_SOURCE=${SEED_SOURCE/#\~/$HOME}
  mkdir -p "$SEED_DIR"
  if [[ -f "$SEED_SOURCE" ]]; then
    unzip -o -j "$SEED_SOURCE" -x '__MACOSX/*' '.*' -d "$SEED_DIR" >/dev/null
  elif [[ -d "$SEED_SOURCE" ]]; then
    cp "$SEED_SOURCE"/* "$SEED_DIR"/
  else
    warn "no such path: $SEED_SOURCE"
    exit 1
  fi
  note "copied into $SEED_DIR; these files stay out of git"
fi
pause

stage "The LLM key"
say "Cognify calls DeepSeek, so the API process needs a key in $ENV_FILE."
[[ -f "$ENV_FILE" ]] || cp "$SERVER_DIR/.env.example" "$ENV_FILE"
if grep -qE '^LLM_API_KEY=sk-\.\.\.$|^LLM_API_KEY=$' "$ENV_FILE" || ! grep -q '^LLM_API_KEY=' "$ENV_FILE"; then
  open_url "https://platform.deepseek.com/api_keys"
  step "Sign in, then 'Create new API key' and copy it (it is shown once)."
  ask_secret LLM_API_KEY "Paste the DeepSeek key:"
  write_env LLM_API_KEY "$LLM_API_KEY"
else
  note "$ENV_FILE already carries an LLM_API_KEY, leaving it alone"
fi
pause

stage "The running API"
say "Seeding drives the HTTP API, so it has to be up with those settings loaded."
if curl -fsS "$API/health" >/dev/null 2>&1; then
  note "$API is already answering"
else
  step "In another terminal, from $SERVER_DIR:"
  note "  sudo service postgresql start   # or: docker compose up postgres"
  note "  uv run alembic upgrade head"
  note "  uv run uvicorn lattice.main:app --reload"
  until curl -fsS "$API/health" >/dev/null 2>&1; do
    pause "Press Enter once it is listening on $API"
  done
  note "$API is answering"
fi
pause

stage "Seed, after the cost"
say "First-time Cognify of a deck spends real LLM calls; re-seeding the same bytes spends none."
uv run python scripts/seed_course.py \
  --course "$COURSE_CODE" --name "$COURSE_NAME" --api "$API" --dry-run
printf '\n'
warn "the dollar figure above is an order of magnitude, not a quote"
if confirm "Upload these and wait for them to cognify?"; then
  uv run python scripts/seed_course.py \
    --course "$COURSE_CODE" --name "$COURSE_NAME" --api "$API" --yes \
    || SKIPPED+=("some Materials did not reach 'ready'; check /materials.list and retry them")
else
  SKIPPED+=("seeding itself: re-run this wizard, or scripts/seed_course.py --course $COURSE_CODE")
fi

finish
